title: "Zachary Fetters"
author:
  name: "Zachary Fetters"
  email: "hey@attkzach.gay"
description: "My name is Zachary and I am a graphic designer and web developer."

baseurl: ""
url: "https://attkzach.gay"

safe: true
disable_disk_cache: true
timezone: "America/Kentucky/Monticello"
encoding: "utf-8"
future: true
show_drafts: false
unpublished: false
incremental: true
highlighter: none

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-external-links

sass:
  style: compressed

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank

kramdown:
    syntax_highlighter_opts:
      disable: true

include: ["_pages", "__*.css"]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "netlify.toml",
  "package.json",
  "package-lock.json",
  ".gitattributes",
  ".gitignore",
  "_config.yml",
  "LICENSE",
  "README.md"
]

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/
      layout: default
      top-level: true #show in navbar
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /:categories/:title/
      layout: writeup
      categories: writeup