title: "attkzach"
author:
  name: "attkzach"
  email: "null"
description: Welcome to my website, my name is Zachary! I am a hobbyist web developer, graphic designer, and overall tech nerd.

baseurl: ""
url: "https://attkzach.gay"
prettyurl: "attkzach.gay"

safe: false
disable_disk_cache: true
timezone: "America/New_York"
encoding: "utf-8"
future: false
show_drafts: false
unpublished: false
incremental: false
highlighter: none

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-link-attributes

sass:
  style: compressed

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank

kramdown:
    syntax_highlighter_opts:
      disable: true

include: ["_pages"]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "netlify.toml",
  "package.json",
  "package-lock.json",
  ".gitattributes",
  ".gitignore",
  "_config.yml",
  "LICENSE",
  "README.md",
  "build.sh"
]

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: default
      site-nav: true
      permalink: /:basename/