title: "Zach Fetters"
author:
  name: "Zach Fetters"
  email: "zachfett@protonmail.com"
description: Welcome to my website, my name is Zachary! I am a hobbyist web developer, graphic designer, and overall tech nerd.

baseurl: ""
url: "https://zachfetters.com"

safe: false
disable_disk_cache: true
timezone: "America/New_York"
encoding: "utf-8"
future: false
show_drafts: false
unpublished: false
incremental: false
highlighter: none

plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-sitemap

sass:
  style: compressed

target-blank:
    noopener: false
    noreferrer: false

kramdown:
    syntax_highlighter_opts:
      disable: true

include: ["_pages"]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "netlify.toml",
  "package.json",
  "package-lock.json",
  ".gitattributes",
  ".gitignore",
  "_config.yml",
  "LICENSE",
  "README.md",
  "build.sh"
]

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: default
      site-nav: true
      permalink: /:basename/