backend:
  name: git-gateway
  branch: main

media_folder: "assets/image/hotlink-ok/attachment"
site_url: https://attkzach.gay
logo_url: https://attkzach.gay/assets/image/brand/attkzach_logo_color.svg
locale: "en"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "data"
    label: "Site Data"
    files:
      - label: "External Links"
        name: "external-links"
        file: "_data/external-links.yml"
        fields:
          - name: "link"
            widget: "list"
            fields:
              - {label: "Link Title", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Icon Name", name: "icon", widget: "string"}
      - label: "Webrings"
        name: "webrings"
        file: "_data/webrings.yml"
        fields:
          - name: "webring"
            widget: "list"
            fields:
              - {label: "Webring Name", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "'Previous' Link", name: "prev_url", widget: "string"}
              - {label: "'Next' Link", name: "next_url", widget: "string"}
              - {label: "'Random' Link", name: "rand_url", widget: "string", default: ""}
  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    create: true
    slug: "{{slug}}"
    preview_path: /{{title}}
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Show in navigation?", name: "show_in_nav", widget: "boolean", default: "true"}
      - {label: "Navigation Group", name: "nav_group", widget: "select", options: ["main", "misc"], default: "main"}
      - {label: "Navigation Position", name: "nav_position", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: blog/{{title}}/
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Published?", name: "published", widget: "boolean"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        max: 4
        min: 1
        default: ["technology"]
      - label: "Authors"
        name: "authors"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Name", name: "name", widget: "string", default: "Zachary Fetters"}
          - {label: "Email", name: "email", widget: "string", default: "hey@attkzach.gay"}
      - {label: "Body", name: "body", widget: "markdown"}